image:
  name: 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/pipeline-images-deb-python37-docker:latest
  aws:
    access-key: $AWS_ECR_ACCESS
    secret-key: $AWS_ECR_SECRET

options:
  docker: True

pipelines:
  branches:
    master:
      - step:
          name: Build and push images
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ECR_PUSH_ACCESS
            - export AWS_SECRET_ACCESS_KEY=$AWS_ECR_PUSH_SECRET

            - aws ecr get-login --no-include-email | bash
            - aws ecr create-repository --repository-name $BITBUCKET_REPO_SLUG || true

            - docker build --tag $BITBUCKET_REPO_SLUG:staging .

            - docker tag $BITBUCKET_REPO_SLUG:staging 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:staging
            - docker tag $BITBUCKET_REPO_SLUG:staging 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:latest
            - docker tag $BITBUCKET_REPO_SLUG:staging 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER

            - docker push 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:staging
            - docker push 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:latest
            - docker push 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER

      - step:
          name: Deploy to ECS
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ECS_DEPLOYMENTS_ACCESS
            - export AWS_SECRET_ACCESS_KEY=$AWS_ECS_DEPLOYMENTS_SECRET

            - python deployment/deploy.py staging

    production:
      - step:
          name:  Build and push images
          script:
          - export AWS_ACCESS_KEY_ID=$AWS_ECR_PUSH_ACCESS
          - export AWS_SECRET_ACCESS_KEY=$AWS_ECR_PUSH_SECRET

          - aws ecr get-login --no-include-email | bash
          - aws ecr create-repository --repository-name $BITBUCKET_REPO_SLUG || true

          - docker build --tag $BITBUCKET_REPO_SLUG:production .

          - docker tag $BITBUCKET_REPO_SLUG:production 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:production
          - docker tag $BITBUCKET_REPO_SLUG:production 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER

          - docker push 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:production
          - docker push 176334869423.dkr.ecr.ap-southeast-2.amazonaws.com/$BITBUCKET_REPO_SLUG:$BITBUCKET_BUILD_NUMBER

      - step:
          name: Deploy to ECS
          script:
          - export AWS_ACCESS_KEY_ID=$AWS_ECS_DEPLOYMENTS_ACCESS
          - export AWS_SECRET_ACCESS_KEY=$AWS_ECS_DEPLOYMENTS_SECRET

          - python deployment/deploy.py production
