backend:
  name: github
  repo: shadow81627/static-cms
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "page" # Used in routes, e.g., /admin/collections/page
    label: "Pages" # Used in the UI
    format: 'json'
    files:
      - label: "Sign up"
        name: signup
        file: "content/page/signup.json"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Description
            name: description
            widget: object
            fields:
              - {label: heading, name: heading, widget: string}
              - {label: subheading, name: subheading, widget: string}
              - {label: paragraph, name: paragraph, widget: markdown}
  - name: "social" # Used in routes, e.g., /admin/collections/blog
    label: "Social" # Used in the UI
    files:
      - label: Facebook
        name: facebook
        file: "content/social/facebook.json"
        fields:
          - label: App
            name: app
            widget: object
            fields:
            - {label: App ID, name: id, widget: string}
            - {label: Version, name: version, widget: string}
      - label: Twitter
        name: twitter
        file: "content/social/twitter.json"
        fields:
          - {label: Text, name: text, widget: string}
      - label: OG
        name: og
        file: "content/social/og.json"
        fields:
          - {label: URL, name: url, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Image, name: image, widget: image}
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Cover Image", name: "image", widget: "image", optional: true, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "SEO Description", name: "description", widget: "text"}
    card: {type: "image", image: "image", text: "title"}
